export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT'
export const GET_NEW_STUDENTS = 'GET_NEW_STUDENTS'
export const NEW_STUDENTS_LOADING = 'NEW_STUDENT_LOADING'

export const GET_ANNOUNCEMENT_REQUEST = 'GET_ANNOUNCEMENT_REQUEST'
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS'
export const GET_ANNOUNCEMENT_FAILED = 'GET_ANNOUNCEMENT_FAILED'
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT'
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT'
