export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT'
export const GET_NEW_STUDENTS = 'GET_NEW_STUDENTS'
export const NEW_STUDENTS_LOADING = 'NEW_STUDENT_LOADING'
export const EDIT_NEW_STUDENT = 'EDIT_NEW_STUDENT'

export const GET_ANNOUNCEMENT_REQUEST = 'GET_ANNOUNCEMENT_REQUEST'
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS'
export const GET_ANNOUNCEMENT_FAILED = 'GET_ANNOUNCEMENT_FAILED'
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT'
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT'

export const STUDENTS_LOADING = 'STUDENTS_LOADING'
export const ADD_STUDENT = 'ADD_STUDENT'
export const GET_STUDENTS = 'GET_STUDENTS'

export const USERS_LOADING = 'USERS_LOADING'
export const USERS_LOADED = 'USERS_LOADED'
export const REGISTER_SUCCESS = 'GET_STUDENTS'
export const REGISTER_FAIL = 'GET_STUDENTS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'



